# Generated by Django 5.0.3 on 2024-03-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniq_id', models.UUIDField()),
                ('product_name', models.CharField(max_length=500)),
                ('product_category_tree', models.CharField(max_length=500)),
                ('retail_price', models.IntegerField()),
                ('image', models.URLField()),
                ('description', models.CharField(max_length=500)),
                ('brand', models.CharField(max_length=100)),
            ],
        ),
    ]
