# Generated by Django 5.0.3 on 2024-03-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uniq_id',
            field=models.CharField(max_length=500),
        ),
    ]
