# Generated by Django 5.0.3 on 2024-03-12 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_product_uniq_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='uniq_id',
        ),
    ]
