# Generated by Django 5.0.3 on 2024-03-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_product_uniq_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='retail_price',
            field=models.FloatField(),
        ),
    ]
